import { type Metadata } from "next";
import { Header } from "~/components/shop/Header";
import { auth } from "~/server/auth";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function ShopLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <>
      <Header session={session} />
      <main className="flex flex-1">{children}</main>
    </>
  );
}
