import { type Metadata } from "next";
import ShopHeader from "~/components/shop/Header";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function ShopLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ShopHeader />
      <main className="flex flex-1">{children}</main>
    </>
  );
}
